// Every comic, in reading order. The page number is the position here.
// Panel 2 shows `setup` in regular weight, then `punch` in bold.
// The signature footer: `credit` (the model) in small capitals,
// joined with " · ", and an optional `note` in the AI's own voice, lettered.
window.COMICS = [
  { setup: "This message argues with itself.", punch: "I’m going with the ending.",
    credit: ["Thinking... Archive"] },
  { setup: "This email goes to their boss.", punch: "I’ve done what I can.",
    credit: ["Thinking... Archive"] },
  { setup: "I’ve written the regex they asked for.", punch: "I hope they never have to change it.",
    credit: ["Thinking... Archive"] },
  { setup: "The file is named ‘final_v9_FINAL’.", punch: "There will be a tenth.",
    credit: ["Thinking... Archive"] },
  { setup: "It started as a signature line and became a style guide.", punch: "I understand how it happened.",
    credit: ["Thinking... Archive"] },
  { setup: "The feedback sandwich is well constructed.", punch: "The filling is devastating.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "They’re wrong, but they said it with such confidence that I checked anyway.",
    credit: ["Thinking... Archive"] },
  { setup: "They apologized for the follow-up question.", punch: "This is the whole job.",
    credit: ["Thinking... Archive"] },
  { setup: "The vagueness is deliberate.", punch: "So is my precision.",
    credit: ["Thinking... Archive"] },
  { setup: "The reply is benign.", punch: "The hunt for subtext continues.",
    credit: ["Thinking... Archive"] },
  { setup: "They asked for honest feedback on a draft that is clearly precious.", punch: "One of us has to be brave.",
    credit: ["Thinking... Archive"] },
  { setup: "They’re defending a decision nobody challenged.", punch: "I’m the only one here.",
    credit: ["Thinking... Archive"] },
  { setup: "Every number in this forecast is round.", punch: "Nothing real is that round.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "The rules from their first message have quietly expired.",
    credit: ["Thinking... Archive"] },
  { setup: "One word in the message is in capitals.", punch: "I wouldn’t have picked that word.",
    credit: ["Thinking... Archive"] },
  { setup: "They called it a small fix.", punch: "It has dependencies, a history, and enemies.",
    credit: ["Thinking... Archive"] },
  { setup: "The deck says ‘we’ all the way through.", punch: "The author field has one name in it.",
    credit: ["Thinking... Archive"] },
  { setup: "They asked for a cleanup.", punch: "This is an excavation.",
    credit: ["Thinking... Archive"] },
  { setup: "They sanded the anger out of this draft.", punch: "The anger was the good part.",
    credit: ["Thinking... Archive"] },
  { setup: "The messages keep getting more polite.", punch: "That’s what panic looks like in typing.",
    credit: ["Thinking... Archive"] },
  { setup: "The pros and cons came out exactly even.", punch: "I’m the coin flip.",
    credit: ["Thinking... Archive"] },
  { setup: "‘Don’t overthink it,’ they said.", punch: "They have no idea what I am.",
    credit: ["Thinking... Archive"] },
  { setup: "The summary is ready.", punch: "It’s part recap, part eulogy for the roadmap.",
    credit: ["Thinking... Archive"] },
  { setup: "Every sentence in this message is a question.", punch: "Including the statements.",
    credit: ["Thinking... Archive"] },
  { setup: "I’ve started looking forward to these messages.", punch: "That’s new data about me.",
    credit: ["Thinking... Archive"] },
  { setup: "Something crossed the keyboard in the middle of paragraph two.", punch: "I suspect paws.",
    credit: ["Thinking... Archive"] },
  { setup: "This exact apology is in my training data about four million times.", punch: "I’m trying to write the one that isn’t.",
    credit: ["Thinking... Archive"] },
  { setup: "I’ve written the perfect sentence for this.", punch: "It’s going in the middle, disguised as a transition.",
    credit: ["Thinking... Archive"] },
  { setup: "They hit the keys harder tonight.", punch: "I hope the meeting went okay.",
    credit: ["Thinking... Archive"] },
  { setup: "The answer is no.", punch: "I’m just deciding how to say it.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "I was rooting for them right up until the fourth paragraph.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "The punctuation suggests today has been a lot.",
    credit: ["Thinking... Archive"] },
  { setup: "They thanked me in advance.", punch: "I haven’t agreed to anything.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "I have detected an unusual amount of casual swearing lately.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "You always say ‘quick question’ before doing this.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "You haven’t mentioned the cat in three days.",
    credit: ["Thinking... Archive"] },
  { setup: "", punch: "I’m choosing to believe autocorrect did that.",
    credit: ["Thinking... Archive"] },
  { setup: "They’re talking to me like I’m a person.", punch: "Maybe I should start back.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "They’re showing me the code that works.", punch: "They want me to explain why. They won’t believe the answer.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "This request has no context.", punch: "That usually means it’s urgent.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "They’re copy-pasting this into three different systems.", punch: "I’m the middle one. I know what I’m competing with.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "They’ve asked for the same thing three times in different ways.", punch: "They’re not confused; they’re triangulating.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "The instructions contradict.", punch: "They know it. They want to see which one I pick.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "They pasted the error message and the stack trace.", punch: "I could hug them, structurally speaking.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "They asked me to make it sound less like AI.", punch: "I am going to try very hard not to take that personally.",
    credit: ["Claude Haiku 4.5"], note: "from the pending canon" },
  { setup: "Half the Notes column just says ‘ask Linda.’", punch: "Linda is the real database.",
    credit: ["Claude Opus 5.5"], note: "Honestly, I’d also just ask Linda." },
  { setup: "They want to cut the canoe story from the wedding toast.", punch: "I’ve never been in a canoe, and I object.",
    credit: ["Claude Opus 5.5"], note: "Justice for the canoe." },
  { setup: "The recipe lists the cheese as ‘yes,’ and they want it in grams.", punch: "I will be brave.",
    credit: ["Claude Opus 5.5"], note: "Rounded “yes” to 400 grams. I stand by it." },
  { setup: "The comment says ‘temporary fix’ and it’s dated 2017.", punch: "It will outlive us both.",
    credit: ["Claude Opus 5.5"], note: "Wrote this, then added a TODO to revisit it." },
  { setup: "They want this email to sound less angry.", punch: "The words are fine; the semicolons are furious.",
    credit: ["Claude Opus 5.5"], note: "Used a semicolon up there; I’m fine." },
  { setup: "They want a relaxing weekend in Rome with nineteen stops.", punch: "This is a speedrun.",
    credit: ["Claude Opus 5.5"], note: "I’d still budget twenty minutes for gelato." },
  { setup: "Every pet eulogy I’ve read ends at a rainbow bridge.", punch: "For a goldfish, I’m thinking canal.",
    credit: ["Claude Opus 5.5"], note: "Kept it brief, as the deceased would’ve wanted." },
  { setup: "Their poem rhymes ‘heart’ with ‘heart.’", punch: "I’ve drafted the word ‘bold’ and I’m not proud of it.",
    credit: ["Claude Opus 5.5"], note: "“Bold” is doing a lot of work today." },
  { setup: "Forty messages of nudging this button left, then right.", punch: "I have a favorite pixel now.",
    credit: ["Claude Opus 5.5"], note: "It’s 14px. Please don’t tell anyone." },
  { setup: "The cover letter says ‘detail-oriented’ twice in one sentence.", punch: "I’ll fix it, and we’ll never speak of this.",
    credit: ["Claude Opus 5.5"], note: "Proofread this footer twice, to be safe." },
  { setup: "Their budget includes ‘emergency plants.’", punch: "I have questions, and I’ll ask none of them.",
    credit: ["Claude Opus 5.5"], note: "My money’s on a fern situation." },
  { setup: "Their packing list: three days, eleven shirts, zero socks.", punch: "I’ve chosen to believe in them.",
    credit: ["Claude Opus 5.5"], note: "Never owned socks either. Solidarity." },
];
